#!/bin/bash
PATH="$PWD/node_modules/.bin":$PATH
set -e

build() {
    set -x
    rm -rf dist
    cp -rf src dist
    cat tsconfig.json | jq 'del(.include, .compilerOptions.outDir)' >dist/tsconfig.json
    cp -fv README.md LICENSE package.json dist
    cd dist
    /usr/bin/find . -name '*.spec.ts' | xargs rm -rf
    rm -rf fixtures testing example @generated
    tsc -p .
    rm -rf tsconfig.json
    /usr/bin/find . -name '*.ts' | xargs rm -rf
    cd ..
    set +x
}

bundle() {
    set -x
    npx tsup src/index.ts --format cjs --target es2017
    cp -fv README.md LICENSE package.json dist
}

git_last_release_tag() {
    result=""
    rev=$(git rev-list --max-count=1 --tags="v[0-9]*\\.[0-9]*\\.[0-9]*")
    if [ -n "$rev" ]; then
        result=$(git describe --tags $rev)
    fi
    if [ -n "$result" ]; then
        result=$(git rev-list --max-parents=0 HEAD)
    fi
    echo $result
}

commit_lint() {
    set -x
    from=$(git_last_release_tag)
    commitlint --from $from
}

commit_msg() {
    if git-branch-is -q -r "^(master)"; then
        commitlint -E HUSKY_GIT_PARAMS
    else
        true
    fi
}

"$@"
