#!/bin/bash
PATH="$PWD/node_modules/.bin":$PATH
set -e

buildMicrobundle6() {
  set -x
  rm -rf dist
  mkdir dist
  dts-bundle-generator --no-banner --project tsconfig.build.json -o dist/index.d.ts src/index.ts
  microbundle build -i src/index.ts --tsconfig ./tsconfig.build.json --no-generateTypes --no-sourcemap --no-compress --no-pkg-main --target node -f esm -o dist
  name=$(cat package.json | jq -r '.name')
  cp -fv src/bin.js dist
  cp -v README.md package.json dist
  cd dist
  mv index.d.ts "$name.d.ts"
  mv "$name.js" "$name.mjs"
  cat ../package.json | jq --arg name "$name" '
    .module = "./\($name).mjs" |
    .types = "./\($name).d.ts" |
    .exports.".".default = "./\($name).mjs"
  ' > package.json
  cd ..
  set +x
}

compatibilty_check() {
  set -x
  rm -rf ./@generated && npm run prisma:g && npm run tscheck

  echo === Check noAtomicOperations ===
  sed -i 's/noAtomicOperations *= false/noAtomicOperations = true/g' prisma/schema.prisma
  rm -rf ./@generated && npm run prisma:g && npm run tscheck
  sed -i 's/noAtomicOperations *= true/noAtomicOperations = false/g' prisma/schema.prisma

  echo === Check combineScalarFilters ===
  sed -i 's/combineScalarFilters *= false/combineScalarFilters = true/g' prisma/schema.prisma
  rm -rf ./@generated && npm run prisma:g && npm run tscheck
  sed -i 's/combineScalarFilters *= true/combineScalarFilters = false/g' prisma/schema.prisma

  echo === Switching reExport ===
  sed -i 's/reExport *= None/reExport = All/g' prisma/schema.prisma
  rm -rf ./@generated && npm run prisma:g && npm run tscheck
  sed -i 's/reExport *= All/reExport = None/g' prisma/schema.prisma

  echo === Check emitSingle ===
  sed -i 's/emitSingle *= false/emitSingle = true/g' prisma/schema.prisma
  rm -rf ./@generated && npm run prisma:g
  npx tsc --noEmit --skipLibCheck --experimentalDecorators ./@generated/index.ts
  npx tsc --noEmit ./@generated/index.ts

  echo === Check emitCompiled ===
  sed -i 's/emitCompiled *= false/emitCompiled = true/g' prisma/schema.prisma
  rm -rf ./@generated && npm run prisma:g
  node ./@generated/index.js

  sed -i 's/emitCompiled *= true/emitCompiled = false/g' prisma/schema.prisma
  sed -i 's/emitSingle *= true/emitSingle = false/g' prisma/schema.prisma

  echo === Check requireSingleFieldsInWhereUniqueInput ===
  sed -i 's/requireSingleFieldsInWhereUniqueInput *= false/requireSingleFieldsInWhereUniqueInput = true/g' prisma/schema.prisma
  rm -rf ./@generated && npm run prisma:g && npm run tscheck
  sed -i 's/requireSingleFieldsInWhereUniqueInput *= true/requireSingleFieldsInWhereUniqueInput = false/g' prisma/schema.prisma

  set +x
}

"$@"
