#!/bin/bash
PATH="$PWD/node_modules/.bin":$PATH
set -e

buildMicrobundle6() {
  set -x
  rm -rf dist
  mkdir dist
  name=$(cat package.json | jq -r '.name')
  dts-bundle-generator --no-banner --project tsconfig.json -o "dist/$name.d.ts" src/generate.ts
  microbundle build -i src/generate.ts --no-generateTypes --no-sourcemap --no-compress --no-pkg-main --target node -f esm -o dist
  cp -fv src/bin.mjs dist
  cp -v README.md package.json dist
  cd dist
  mv "$name.js" "$name.mjs"
  cat ../package.json | jq --arg name "$name" '
    .exports.".".default = "./\($name).mjs" |
    .exports.".".types = "./\($name).d.ts"
  ' > package.json

  set +x
}

compatibilty_check() {
  if [ -n "$(git status --porcelain)" ]; then
    echo "Repository is not clean. Commit, stash, or discard all changes before running compatibilty_check"
    git status --short
    exit 1
  fi

  set -x
  rm -rf ./@generated && npm run prisma:g && npm run tscheck

  echo === Check noAtomicOperations ===
  sed -i 's/noAtomicOperations *= false/noAtomicOperations = true/g' prisma/schema.prisma
  rm -rf ./@generated && npm run prisma:g && npm run tscheck
  sed -i 's/noAtomicOperations *= true/noAtomicOperations = false/g' prisma/schema.prisma

  echo === Check combineScalarFilters ===
  sed -i 's/combineScalarFilters *= false/combineScalarFilters = true/g' prisma/schema.prisma
  rm -rf ./@generated && npm run prisma:g && npm run tscheck
  sed -i 's/combineScalarFilters *= true/combineScalarFilters = false/g' prisma/schema.prisma

  echo === Switching reExport ===
  sed -i 's/reExport *= All/reExport = None/g' prisma/schema.prisma
  rm -rf ./@generated && npm run prisma:g && npm run tscheck
  sed -i 's/reExport *= None/reExport = All/g' prisma/schema.prisma

  echo === Check emitSingle ===
  sed -i 's/emitSingle *= false/emitSingle = true/g' prisma/schema.prisma
  rm -rf ./@generated && npm run prisma:g
  npx tsc --noEmit --skipLibCheck --experimentalDecorators --ignoreConfig ./@generated/index.ts

  echo === Check emitCompiled ===
  sed -i 's/emitCompiled *= false/emitCompiled = true/g' prisma/schema.prisma
  rm -rf ./@generated && npm run prisma:g
  node ./@generated/index.js

  sed -i 's/emitCompiled *= true/emitCompiled = false/g' prisma/schema.prisma
  sed -i 's/emitSingle *= true/emitSingle = false/g' prisma/schema.prisma

  echo === Check requireSingleFieldsInWhereUniqueInput ===
  sed -i 's/requireSingleFieldsInWhereUniqueInput *= false/requireSingleFieldsInWhereUniqueInput = true/g' prisma/schema.prisma
  rm -rf ./@generated && npm run prisma:g && npm run tscheck
  sed -i 's/requireSingleFieldsInWhereUniqueInput *= true/requireSingleFieldsInWhereUniqueInput = false/g' prisma/schema.prisma

  set +x
}

"$@"
