
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.ts'
export { Prisma }
export * as $Enums from './enums.ts'
export * from './enums.ts';
/**
 * Model User
 * User really
 */
export type User = Prisma.UserModel
/**
 * Model Tag
 * 
 */
export type Tag = Prisma.TagModel
/**
 * Model Article
 * 
 */
export type Article = Prisma.ArticleModel
/**
 * Model Comment
 * 
 */
export type Comment = Prisma.CommentModel
/**
 * Model Profile
 * 
 */
export type Profile = Prisma.ProfileModel
/**
 * Model Dummy
 * 
 */
export type Dummy = Prisma.DummyModel
