
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/User.ts'
export type * from './models/Tag.ts'
export type * from './models/Article.ts'
export type * from './models/Comment.ts'
export type * from './models/Profile.ts'
export type * from './models/Dummy.ts'
export type * from './commonInputTypes.ts'