
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Dummy` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Dummy
 * 
 */
export type DummyModel = runtime.Types.Result.DefaultSelection<Prisma.$DummyPayload>

export type AggregateDummy = {
  _count: DummyCountAggregateOutputType | null
  _avg: DummyAvgAggregateOutputType | null
  _sum: DummySumAggregateOutputType | null
  _min: DummyMinAggregateOutputType | null
  _max: DummyMaxAggregateOutputType | null
}

export type DummyAvgAggregateOutputType = {
  int: number | null
  float: number | null
  decimal: runtime.Decimal | null
  decimals: runtime.Decimal | null
  bigInt: number | null
}

export type DummySumAggregateOutputType = {
  int: number | null
  float: number | null
  decimal: runtime.Decimal | null
  decimals: runtime.Decimal[]
  bigInt: bigint | null
}

export type DummyMinAggregateOutputType = {
  id: string | null
  date: Date | null
  int: number | null
  float: number | null
  bytes: runtime.Bytes | null
  decimal: runtime.Decimal | null
  bigInt: bigint | null
}

export type DummyMaxAggregateOutputType = {
  id: string | null
  date: Date | null
  int: number | null
  float: number | null
  bytes: runtime.Bytes | null
  decimal: runtime.Decimal | null
  bigInt: bigint | null
}

export type DummyCountAggregateOutputType = {
  id: number
  date: number
  int: number
  float: number
  bytes: number
  decimal: number
  decimals: number
  bigInt: number
  json: number
  friends: number
  _all: number
}


export type DummyAvgAggregateInputType = {
  int?: true
  float?: true
  decimal?: true
  decimals?: true
  bigInt?: true
}

export type DummySumAggregateInputType = {
  int?: true
  float?: true
  decimal?: true
  decimals?: true
  bigInt?: true
}

export type DummyMinAggregateInputType = {
  id?: true
  date?: true
  int?: true
  float?: true
  bytes?: true
  decimal?: true
  bigInt?: true
}

export type DummyMaxAggregateInputType = {
  id?: true
  date?: true
  int?: true
  float?: true
  bytes?: true
  decimal?: true
  bigInt?: true
}

export type DummyCountAggregateInputType = {
  id?: true
  date?: true
  int?: true
  float?: true
  bytes?: true
  decimal?: true
  decimals?: true
  bigInt?: true
  json?: true
  friends?: true
  _all?: true
}

export type DummyAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Dummy to aggregate.
   */
  where?: Prisma.DummyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Dummies to fetch.
   */
  orderBy?: Prisma.DummyOrderByWithRelationInput | Prisma.DummyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DummyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Dummies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Dummies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Dummies
  **/
  _count?: true | DummyCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DummyAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DummySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DummyMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DummyMaxAggregateInputType
}

export type GetDummyAggregateType<T extends DummyAggregateArgs> = {
      [P in keyof T & keyof AggregateDummy]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDummy[P]>
    : Prisma.GetScalarType<T[P], AggregateDummy[P]>
}




export type DummyGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DummyWhereInput
  orderBy?: Prisma.DummyOrderByWithAggregationInput | Prisma.DummyOrderByWithAggregationInput[]
  by: Prisma.DummyScalarFieldEnum[] | Prisma.DummyScalarFieldEnum
  having?: Prisma.DummyScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DummyCountAggregateInputType | true
  _avg?: DummyAvgAggregateInputType
  _sum?: DummySumAggregateInputType
  _min?: DummyMinAggregateInputType
  _max?: DummyMaxAggregateInputType
}

export type DummyGroupByOutputType = {
  id: string
  date: Date | null
  int: number | null
  float: number | null
  bytes: runtime.Bytes | null
  decimal: runtime.Decimal
  decimals: runtime.Decimal[]
  bigInt: bigint | null
  json: runtime.JsonValue | null
  friends: string[]
  _count: DummyCountAggregateOutputType | null
  _avg: DummyAvgAggregateOutputType | null
  _sum: DummySumAggregateOutputType | null
  _min: DummyMinAggregateOutputType | null
  _max: DummyMaxAggregateOutputType | null
}

type GetDummyGroupByPayload<T extends DummyGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DummyGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DummyGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DummyGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DummyGroupByOutputType[P]>
      }
    >
  >



export type DummyWhereInput = {
  AND?: Prisma.DummyWhereInput | Prisma.DummyWhereInput[]
  OR?: Prisma.DummyWhereInput[]
  NOT?: Prisma.DummyWhereInput | Prisma.DummyWhereInput[]
  id?: Prisma.StringFilter<"Dummy"> | string
  date?: Prisma.DateTimeNullableFilter<"Dummy"> | Date | string | null
  int?: Prisma.IntNullableFilter<"Dummy"> | number | null
  float?: Prisma.FloatNullableFilter<"Dummy"> | number | null
  bytes?: Prisma.BytesNullableFilter<"Dummy"> | runtime.Bytes | null
  decimal?: Prisma.DecimalFilter<"Dummy"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  decimals?: Prisma.DecimalNullableListFilter<"Dummy">
  bigInt?: Prisma.BigIntNullableFilter<"Dummy"> | bigint | number | null
  json?: Prisma.JsonNullableFilter<"Dummy">
  friends?: Prisma.StringNullableListFilter<"Dummy">
}

export type DummyOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrderInput | Prisma.SortOrder
  int?: Prisma.SortOrderInput | Prisma.SortOrder
  float?: Prisma.SortOrderInput | Prisma.SortOrder
  bytes?: Prisma.SortOrderInput | Prisma.SortOrder
  decimal?: Prisma.SortOrder
  decimals?: Prisma.SortOrder
  bigInt?: Prisma.SortOrderInput | Prisma.SortOrder
  json?: Prisma.SortOrderInput | Prisma.SortOrder
  friends?: Prisma.SortOrder
}

export type DummyWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.DummyWhereInput | Prisma.DummyWhereInput[]
  OR?: Prisma.DummyWhereInput[]
  NOT?: Prisma.DummyWhereInput | Prisma.DummyWhereInput[]
  date?: Prisma.DateTimeNullableFilter<"Dummy"> | Date | string | null
  int?: Prisma.IntNullableFilter<"Dummy"> | number | null
  float?: Prisma.FloatNullableFilter<"Dummy"> | number | null
  bytes?: Prisma.BytesNullableFilter<"Dummy"> | runtime.Bytes | null
  decimal?: Prisma.DecimalFilter<"Dummy"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  decimals?: Prisma.DecimalNullableListFilter<"Dummy">
  bigInt?: Prisma.BigIntNullableFilter<"Dummy"> | bigint | number | null
  json?: Prisma.JsonNullableFilter<"Dummy">
  friends?: Prisma.StringNullableListFilter<"Dummy">
}, "id">

export type DummyOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrderInput | Prisma.SortOrder
  int?: Prisma.SortOrderInput | Prisma.SortOrder
  float?: Prisma.SortOrderInput | Prisma.SortOrder
  bytes?: Prisma.SortOrderInput | Prisma.SortOrder
  decimal?: Prisma.SortOrder
  decimals?: Prisma.SortOrder
  bigInt?: Prisma.SortOrderInput | Prisma.SortOrder
  json?: Prisma.SortOrderInput | Prisma.SortOrder
  friends?: Prisma.SortOrder
  _count?: Prisma.DummyCountOrderByAggregateInput
  _avg?: Prisma.DummyAvgOrderByAggregateInput
  _max?: Prisma.DummyMaxOrderByAggregateInput
  _min?: Prisma.DummyMinOrderByAggregateInput
  _sum?: Prisma.DummySumOrderByAggregateInput
}

export type DummyScalarWhereWithAggregatesInput = {
  AND?: Prisma.DummyScalarWhereWithAggregatesInput | Prisma.DummyScalarWhereWithAggregatesInput[]
  OR?: Prisma.DummyScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DummyScalarWhereWithAggregatesInput | Prisma.DummyScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Dummy"> | string
  date?: Prisma.DateTimeNullableWithAggregatesFilter<"Dummy"> | Date | string | null
  int?: Prisma.IntNullableWithAggregatesFilter<"Dummy"> | number | null
  float?: Prisma.FloatNullableWithAggregatesFilter<"Dummy"> | number | null
  bytes?: Prisma.BytesNullableWithAggregatesFilter<"Dummy"> | runtime.Bytes | null
  decimal?: Prisma.DecimalWithAggregatesFilter<"Dummy"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  decimals?: Prisma.DecimalNullableListFilter<"Dummy">
  bigInt?: Prisma.BigIntNullableWithAggregatesFilter<"Dummy"> | bigint | number | null
  json?: Prisma.JsonNullableWithAggregatesFilter<"Dummy">
  friends?: Prisma.StringNullableListFilter<"Dummy">
}

export type DummyCreateInput = {
  id: string
  date?: Date | string | null
  int?: number | null
  float?: number | null
  bytes?: runtime.Bytes | null
  decimal: runtime.Decimal | runtime.DecimalJsLike | number | string
  decimals?: Prisma.DummyCreatedecimalsInput | runtime.Decimal[] | runtime.DecimalJsLike[] | number[] | string[]
  bigInt?: bigint | number | null
  json?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  friends?: Prisma.DummyCreatefriendsInput | string[]
}

export type DummyUncheckedCreateInput = {
  id: string
  date?: Date | string | null
  int?: number | null
  float?: number | null
  bytes?: runtime.Bytes | null
  decimal: runtime.Decimal | runtime.DecimalJsLike | number | string
  decimals?: Prisma.DummyCreatedecimalsInput | runtime.Decimal[] | runtime.DecimalJsLike[] | number[] | string[]
  bigInt?: bigint | number | null
  json?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  friends?: Prisma.DummyCreatefriendsInput | string[]
}

export type DummyUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  int?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  float?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  bytes?: Prisma.NullableBytesFieldUpdateOperationsInput | runtime.Bytes | null
  decimal?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  decimals?: Prisma.DummyUpdatedecimalsInput | runtime.Decimal[] | runtime.DecimalJsLike[] | number[] | string[]
  bigInt?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  json?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  friends?: Prisma.DummyUpdatefriendsInput | string[]
}

export type DummyUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  int?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  float?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  bytes?: Prisma.NullableBytesFieldUpdateOperationsInput | runtime.Bytes | null
  decimal?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  decimals?: Prisma.DummyUpdatedecimalsInput | runtime.Decimal[] | runtime.DecimalJsLike[] | number[] | string[]
  bigInt?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  json?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  friends?: Prisma.DummyUpdatefriendsInput | string[]
}

export type DummyCreateManyInput = {
  id: string
  date?: Date | string | null
  int?: number | null
  float?: number | null
  bytes?: runtime.Bytes | null
  decimal: runtime.Decimal | runtime.DecimalJsLike | number | string
  decimals?: Prisma.DummyCreatedecimalsInput | runtime.Decimal[] | runtime.DecimalJsLike[] | number[] | string[]
  bigInt?: bigint | number | null
  json?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  friends?: Prisma.DummyCreatefriendsInput | string[]
}

export type DummyUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  int?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  float?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  bytes?: Prisma.NullableBytesFieldUpdateOperationsInput | runtime.Bytes | null
  decimal?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  decimals?: Prisma.DummyUpdatedecimalsInput | runtime.Decimal[] | runtime.DecimalJsLike[] | number[] | string[]
  bigInt?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  json?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  friends?: Prisma.DummyUpdatefriendsInput | string[]
}

export type DummyUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  int?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  float?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  bytes?: Prisma.NullableBytesFieldUpdateOperationsInput | runtime.Bytes | null
  decimal?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  decimals?: Prisma.DummyUpdatedecimalsInput | runtime.Decimal[] | runtime.DecimalJsLike[] | number[] | string[]
  bigInt?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  json?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  friends?: Prisma.DummyUpdatefriendsInput | string[]
}

export type DecimalNullableListFilter<$PrismaModel = never> = {
  equals?: runtime.Decimal[] | runtime.DecimalJsLike[] | number[] | string[] | Prisma.ListDecimalFieldRefInput<$PrismaModel> | null
  has?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel> | null
  hasEvery?: runtime.Decimal[] | runtime.DecimalJsLike[] | number[] | string[] | Prisma.ListDecimalFieldRefInput<$PrismaModel>
  hasSome?: runtime.Decimal[] | runtime.DecimalJsLike[] | number[] | string[] | Prisma.ListDecimalFieldRefInput<$PrismaModel>
  isEmpty?: boolean
}

export type StringNullableListFilter<$PrismaModel = never> = {
  equals?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  has?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  hasEvery?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  hasSome?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  isEmpty?: boolean
}

export type DummyCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  int?: Prisma.SortOrder
  float?: Prisma.SortOrder
  bytes?: Prisma.SortOrder
  decimal?: Prisma.SortOrder
  decimals?: Prisma.SortOrder
  bigInt?: Prisma.SortOrder
  json?: Prisma.SortOrder
  friends?: Prisma.SortOrder
}

export type DummyAvgOrderByAggregateInput = {
  int?: Prisma.SortOrder
  float?: Prisma.SortOrder
  decimal?: Prisma.SortOrder
  decimals?: Prisma.SortOrder
  bigInt?: Prisma.SortOrder
}

export type DummyMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  int?: Prisma.SortOrder
  float?: Prisma.SortOrder
  bytes?: Prisma.SortOrder
  decimal?: Prisma.SortOrder
  bigInt?: Prisma.SortOrder
}

export type DummyMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  int?: Prisma.SortOrder
  float?: Prisma.SortOrder
  bytes?: Prisma.SortOrder
  decimal?: Prisma.SortOrder
  bigInt?: Prisma.SortOrder
}

export type DummySumOrderByAggregateInput = {
  int?: Prisma.SortOrder
  float?: Prisma.SortOrder
  decimal?: Prisma.SortOrder
  decimals?: Prisma.SortOrder
  bigInt?: Prisma.SortOrder
}

export type DummyCreatedecimalsInput = {
  set: runtime.Decimal[] | runtime.DecimalJsLike[] | number[] | string[]
}

export type DummyCreatefriendsInput = {
  set: string[]
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type NullableBytesFieldUpdateOperationsInput = {
  set?: runtime.Bytes | null
}

export type DecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type DummyUpdatedecimalsInput = {
  set?: runtime.Decimal[] | runtime.DecimalJsLike[] | number[] | string[]
  push?: runtime.Decimal | runtime.DecimalJsLike | number | string | runtime.Decimal[] | runtime.DecimalJsLike[] | number[] | string[]
}

export type NullableBigIntFieldUpdateOperationsInput = {
  set?: bigint | number | null
  increment?: bigint | number
  decrement?: bigint | number
  multiply?: bigint | number
  divide?: bigint | number
}

export type DummyUpdatefriendsInput = {
  set?: string[]
  push?: string | string[]
}



export type DummySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  int?: boolean
  float?: boolean
  bytes?: boolean
  decimal?: boolean
  decimals?: boolean
  bigInt?: boolean
  json?: boolean
  friends?: boolean
}, ExtArgs["result"]["dummy"]>

export type DummySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  int?: boolean
  float?: boolean
  bytes?: boolean
  decimal?: boolean
  decimals?: boolean
  bigInt?: boolean
  json?: boolean
  friends?: boolean
}, ExtArgs["result"]["dummy"]>

export type DummySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  int?: boolean
  float?: boolean
  bytes?: boolean
  decimal?: boolean
  decimals?: boolean
  bigInt?: boolean
  json?: boolean
  friends?: boolean
}, ExtArgs["result"]["dummy"]>

export type DummySelectScalar = {
  id?: boolean
  date?: boolean
  int?: boolean
  float?: boolean
  bytes?: boolean
  decimal?: boolean
  decimals?: boolean
  bigInt?: boolean
  json?: boolean
  friends?: boolean
}

export type DummyOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "date" | "int" | "float" | "bytes" | "decimal" | "decimals" | "bigInt" | "json" | "friends", ExtArgs["result"]["dummy"]>

export type $DummyPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Dummy"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    date: Date | null
    int: number | null
    float: number | null
    bytes: runtime.Bytes | null
    decimal: runtime.Decimal
    decimals: runtime.Decimal[]
    bigInt: bigint | null
    json: runtime.JsonValue | null
    friends: string[]
  }, ExtArgs["result"]["dummy"]>
  composites: {}
}

export type DummyGetPayload<S extends boolean | null | undefined | DummyDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DummyPayload, S>

export type DummyCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DummyFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DummyCountAggregateInputType | true
  }

export interface DummyDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Dummy'], meta: { name: 'Dummy' } }
  /**
   * Find zero or one Dummy that matches the filter.
   * @param {DummyFindUniqueArgs} args - Arguments to find a Dummy
   * @example
   * // Get one Dummy
   * const dummy = await prisma.dummy.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DummyFindUniqueArgs>(args: Prisma.SelectSubset<T, DummyFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DummyClient<runtime.Types.Result.GetResult<Prisma.$DummyPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Dummy that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DummyFindUniqueOrThrowArgs} args - Arguments to find a Dummy
   * @example
   * // Get one Dummy
   * const dummy = await prisma.dummy.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DummyFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DummyFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DummyClient<runtime.Types.Result.GetResult<Prisma.$DummyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Dummy that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DummyFindFirstArgs} args - Arguments to find a Dummy
   * @example
   * // Get one Dummy
   * const dummy = await prisma.dummy.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DummyFindFirstArgs>(args?: Prisma.SelectSubset<T, DummyFindFirstArgs<ExtArgs>>): Prisma.Prisma__DummyClient<runtime.Types.Result.GetResult<Prisma.$DummyPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Dummy that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DummyFindFirstOrThrowArgs} args - Arguments to find a Dummy
   * @example
   * // Get one Dummy
   * const dummy = await prisma.dummy.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DummyFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DummyFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DummyClient<runtime.Types.Result.GetResult<Prisma.$DummyPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Dummies that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DummyFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Dummies
   * const dummies = await prisma.dummy.findMany()
   * 
   * // Get first 10 Dummies
   * const dummies = await prisma.dummy.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const dummyWithIdOnly = await prisma.dummy.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DummyFindManyArgs>(args?: Prisma.SelectSubset<T, DummyFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DummyPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Dummy.
   * @param {DummyCreateArgs} args - Arguments to create a Dummy.
   * @example
   * // Create one Dummy
   * const Dummy = await prisma.dummy.create({
   *   data: {
   *     // ... data to create a Dummy
   *   }
   * })
   * 
   */
  create<T extends DummyCreateArgs>(args: Prisma.SelectSubset<T, DummyCreateArgs<ExtArgs>>): Prisma.Prisma__DummyClient<runtime.Types.Result.GetResult<Prisma.$DummyPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Dummies.
   * @param {DummyCreateManyArgs} args - Arguments to create many Dummies.
   * @example
   * // Create many Dummies
   * const dummy = await prisma.dummy.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DummyCreateManyArgs>(args?: Prisma.SelectSubset<T, DummyCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Dummies and returns the data saved in the database.
   * @param {DummyCreateManyAndReturnArgs} args - Arguments to create many Dummies.
   * @example
   * // Create many Dummies
   * const dummy = await prisma.dummy.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Dummies and only return the `id`
   * const dummyWithIdOnly = await prisma.dummy.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DummyCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DummyCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DummyPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Dummy.
   * @param {DummyDeleteArgs} args - Arguments to delete one Dummy.
   * @example
   * // Delete one Dummy
   * const Dummy = await prisma.dummy.delete({
   *   where: {
   *     // ... filter to delete one Dummy
   *   }
   * })
   * 
   */
  delete<T extends DummyDeleteArgs>(args: Prisma.SelectSubset<T, DummyDeleteArgs<ExtArgs>>): Prisma.Prisma__DummyClient<runtime.Types.Result.GetResult<Prisma.$DummyPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Dummy.
   * @param {DummyUpdateArgs} args - Arguments to update one Dummy.
   * @example
   * // Update one Dummy
   * const dummy = await prisma.dummy.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DummyUpdateArgs>(args: Prisma.SelectSubset<T, DummyUpdateArgs<ExtArgs>>): Prisma.Prisma__DummyClient<runtime.Types.Result.GetResult<Prisma.$DummyPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Dummies.
   * @param {DummyDeleteManyArgs} args - Arguments to filter Dummies to delete.
   * @example
   * // Delete a few Dummies
   * const { count } = await prisma.dummy.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DummyDeleteManyArgs>(args?: Prisma.SelectSubset<T, DummyDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Dummies.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DummyUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Dummies
   * const dummy = await prisma.dummy.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DummyUpdateManyArgs>(args: Prisma.SelectSubset<T, DummyUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Dummies and returns the data updated in the database.
   * @param {DummyUpdateManyAndReturnArgs} args - Arguments to update many Dummies.
   * @example
   * // Update many Dummies
   * const dummy = await prisma.dummy.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Dummies and only return the `id`
   * const dummyWithIdOnly = await prisma.dummy.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DummyUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DummyUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DummyPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Dummy.
   * @param {DummyUpsertArgs} args - Arguments to update or create a Dummy.
   * @example
   * // Update or create a Dummy
   * const dummy = await prisma.dummy.upsert({
   *   create: {
   *     // ... data to create a Dummy
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Dummy we want to update
   *   }
   * })
   */
  upsert<T extends DummyUpsertArgs>(args: Prisma.SelectSubset<T, DummyUpsertArgs<ExtArgs>>): Prisma.Prisma__DummyClient<runtime.Types.Result.GetResult<Prisma.$DummyPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Dummies.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DummyCountArgs} args - Arguments to filter Dummies to count.
   * @example
   * // Count the number of Dummies
   * const count = await prisma.dummy.count({
   *   where: {
   *     // ... the filter for the Dummies we want to count
   *   }
   * })
  **/
  count<T extends DummyCountArgs>(
    args?: Prisma.Subset<T, DummyCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DummyCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Dummy.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DummyAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DummyAggregateArgs>(args: Prisma.Subset<T, DummyAggregateArgs>): Prisma.PrismaPromise<GetDummyAggregateType<T>>

  /**
   * Group by Dummy.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DummyGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DummyGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DummyGroupByArgs['orderBy'] }
      : { orderBy?: DummyGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DummyGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDummyGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Dummy model
 */
readonly fields: DummyFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Dummy.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DummyClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Dummy model
 */
export interface DummyFieldRefs {
  readonly id: Prisma.FieldRef<"Dummy", 'String'>
  readonly date: Prisma.FieldRef<"Dummy", 'DateTime'>
  readonly int: Prisma.FieldRef<"Dummy", 'Int'>
  readonly float: Prisma.FieldRef<"Dummy", 'Float'>
  readonly bytes: Prisma.FieldRef<"Dummy", 'Bytes'>
  readonly decimal: Prisma.FieldRef<"Dummy", 'Decimal'>
  readonly decimals: Prisma.FieldRef<"Dummy", 'Decimal[]'>
  readonly bigInt: Prisma.FieldRef<"Dummy", 'BigInt'>
  readonly json: Prisma.FieldRef<"Dummy", 'Json'>
  readonly friends: Prisma.FieldRef<"Dummy", 'String[]'>
}
    

// Custom InputTypes
/**
 * Dummy findUnique
 */
export type DummyFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dummy
   */
  select?: Prisma.DummySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dummy
   */
  omit?: Prisma.DummyOmit<ExtArgs> | null
  /**
   * Filter, which Dummy to fetch.
   */
  where: Prisma.DummyWhereUniqueInput
}

/**
 * Dummy findUniqueOrThrow
 */
export type DummyFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dummy
   */
  select?: Prisma.DummySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dummy
   */
  omit?: Prisma.DummyOmit<ExtArgs> | null
  /**
   * Filter, which Dummy to fetch.
   */
  where: Prisma.DummyWhereUniqueInput
}

/**
 * Dummy findFirst
 */
export type DummyFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dummy
   */
  select?: Prisma.DummySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dummy
   */
  omit?: Prisma.DummyOmit<ExtArgs> | null
  /**
   * Filter, which Dummy to fetch.
   */
  where?: Prisma.DummyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Dummies to fetch.
   */
  orderBy?: Prisma.DummyOrderByWithRelationInput | Prisma.DummyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Dummies.
   */
  cursor?: Prisma.DummyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Dummies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Dummies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Dummies.
   */
  distinct?: Prisma.DummyScalarFieldEnum | Prisma.DummyScalarFieldEnum[]
}

/**
 * Dummy findFirstOrThrow
 */
export type DummyFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dummy
   */
  select?: Prisma.DummySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dummy
   */
  omit?: Prisma.DummyOmit<ExtArgs> | null
  /**
   * Filter, which Dummy to fetch.
   */
  where?: Prisma.DummyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Dummies to fetch.
   */
  orderBy?: Prisma.DummyOrderByWithRelationInput | Prisma.DummyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Dummies.
   */
  cursor?: Prisma.DummyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Dummies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Dummies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Dummies.
   */
  distinct?: Prisma.DummyScalarFieldEnum | Prisma.DummyScalarFieldEnum[]
}

/**
 * Dummy findMany
 */
export type DummyFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dummy
   */
  select?: Prisma.DummySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dummy
   */
  omit?: Prisma.DummyOmit<ExtArgs> | null
  /**
   * Filter, which Dummies to fetch.
   */
  where?: Prisma.DummyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Dummies to fetch.
   */
  orderBy?: Prisma.DummyOrderByWithRelationInput | Prisma.DummyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Dummies.
   */
  cursor?: Prisma.DummyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Dummies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Dummies.
   */
  skip?: number
  distinct?: Prisma.DummyScalarFieldEnum | Prisma.DummyScalarFieldEnum[]
}

/**
 * Dummy create
 */
export type DummyCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dummy
   */
  select?: Prisma.DummySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dummy
   */
  omit?: Prisma.DummyOmit<ExtArgs> | null
  /**
   * The data needed to create a Dummy.
   */
  data: Prisma.XOR<Prisma.DummyCreateInput, Prisma.DummyUncheckedCreateInput>
}

/**
 * Dummy createMany
 */
export type DummyCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Dummies.
   */
  data: Prisma.DummyCreateManyInput | Prisma.DummyCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Dummy createManyAndReturn
 */
export type DummyCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dummy
   */
  select?: Prisma.DummySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Dummy
   */
  omit?: Prisma.DummyOmit<ExtArgs> | null
  /**
   * The data used to create many Dummies.
   */
  data: Prisma.DummyCreateManyInput | Prisma.DummyCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Dummy update
 */
export type DummyUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dummy
   */
  select?: Prisma.DummySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dummy
   */
  omit?: Prisma.DummyOmit<ExtArgs> | null
  /**
   * The data needed to update a Dummy.
   */
  data: Prisma.XOR<Prisma.DummyUpdateInput, Prisma.DummyUncheckedUpdateInput>
  /**
   * Choose, which Dummy to update.
   */
  where: Prisma.DummyWhereUniqueInput
}

/**
 * Dummy updateMany
 */
export type DummyUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Dummies.
   */
  data: Prisma.XOR<Prisma.DummyUpdateManyMutationInput, Prisma.DummyUncheckedUpdateManyInput>
  /**
   * Filter which Dummies to update
   */
  where?: Prisma.DummyWhereInput
  /**
   * Limit how many Dummies to update.
   */
  limit?: number
}

/**
 * Dummy updateManyAndReturn
 */
export type DummyUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dummy
   */
  select?: Prisma.DummySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Dummy
   */
  omit?: Prisma.DummyOmit<ExtArgs> | null
  /**
   * The data used to update Dummies.
   */
  data: Prisma.XOR<Prisma.DummyUpdateManyMutationInput, Prisma.DummyUncheckedUpdateManyInput>
  /**
   * Filter which Dummies to update
   */
  where?: Prisma.DummyWhereInput
  /**
   * Limit how many Dummies to update.
   */
  limit?: number
}

/**
 * Dummy upsert
 */
export type DummyUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dummy
   */
  select?: Prisma.DummySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dummy
   */
  omit?: Prisma.DummyOmit<ExtArgs> | null
  /**
   * The filter to search for the Dummy to update in case it exists.
   */
  where: Prisma.DummyWhereUniqueInput
  /**
   * In case the Dummy found by the `where` argument doesn't exist, create a new Dummy with this data.
   */
  create: Prisma.XOR<Prisma.DummyCreateInput, Prisma.DummyUncheckedCreateInput>
  /**
   * In case the Dummy was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DummyUpdateInput, Prisma.DummyUncheckedUpdateInput>
}

/**
 * Dummy delete
 */
export type DummyDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dummy
   */
  select?: Prisma.DummySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dummy
   */
  omit?: Prisma.DummyOmit<ExtArgs> | null
  /**
   * Filter which Dummy to delete.
   */
  where: Prisma.DummyWhereUniqueInput
}

/**
 * Dummy deleteMany
 */
export type DummyDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Dummies to delete
   */
  where?: Prisma.DummyWhereInput
  /**
   * Limit how many Dummies to delete.
   */
  limit?: number
}

/**
 * Dummy without action
 */
export type DummyDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Dummy
   */
  select?: Prisma.DummySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Dummy
   */
  omit?: Prisma.DummyOmit<ExtArgs> | null
}
