name: Continuous Integration
on:
  - push
  - pull_request

jobs:
  build:
    name: 'Test, build, release'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v6

      - name: 'Setup Node'
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: 'Install Depependencies'
        run: yarn install

      - name: 'Regenerate'
        run: npm run regen

      - name: 'ESLint'
        run: |
          npm run eslint

      - name: 'tscheck'
        run: |
          npm run tscheck

      - name: 'Test'
        run: |
          npm run test:r -- --bail

      - name: 'Test Build'
        run: |
          npm run build

      - name: 'Compatibilty Check'
        run: |
          npm run compatibilty_check

      - name: 'Release'
        if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/next')
        run: |
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
